### ISSUE TITLE
Incompatible with Firefox 61

### ISSUE THREAD

**Issue by mythmon** [mozilla/pioneer-enrollment-study#6]
This add-on is incompatible with Firefox 61 due to the changes in [bug 1446585](https://bugzilla.mozilla.org/show_bug.cgi?id=1446585).

Specifically, it throws this error immediately on startup:

```
[Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/mythmon/.mozilla/firefox/p4pswihx.pioneer%20enroll%20test/extensions/pioneer-enrollment-study@mozilla.org.xpi!/bootstrap.js :: this.startup :: line 262"  data: no] 
```

Rob Helmer suggests that this is caused by not being able to use `chrome.manifest` to register `resource://` urls anymore. Something like what [form autofill did](https://searchfox.org/mozilla-central/source/browser/extensions/formautofill/bootstrap.js#82-83) will be needed to import files again.

**Comment by motin** [comment]
Additional note: this add-on is a legacy bootstrapped add-on and needs to be ported to a web extension structure to be able to work in Firefox 65+
